version: "3.8"

services:
  app:
    image: konstruktor:latest
    container_name: konstruktor-app
    restart: always
    env_file:
      - .env
    expose:
      - "8080"

  nginx:
    image: nginx:latest
    container_name: konstruktor-nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - app
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt

  certbot:
    image: certbot/certbot
    container_name: konstruktor-certbot
    volumes:
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt
