services:
  konstruktor-app:
    build: .
    image: konstruktor:latest
    container_name: konstruktor-app
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "8080:8080"
    restart: always