import type { Metadata } from "next";
import "./globals.css";
import { ThemeProvider } from "@mui/material";
import ThemeMUI from "@/styles/ThemeMUI";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v13-appRouter";
import SessionWrapper from "@/components/SessionWrapper";
import { ModalProvider } from "@/hooks/useModal";
import SnackbarProviderClient from "@/components/SnackbarProviderClient";
import { HeaderProvider } from "@/hooks/HeaderContext";
import Header from "@/components/Header/Header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ru">
      <body>
        <SessionWrapper>
          <AppRouterCacheProvider>
            <ThemeProvider theme={ThemeMUI}>
              <ModalProvider>
                <SnackbarProviderClient>
                  <HeaderProvider>
                    <Header>
                      {children}
                    </Header>
                  </HeaderProvider>
                </SnackbarProviderClient>
              </ModalProvider>
            </ThemeProvider>
          </AppRouterCacheProvider>
        </SessionWrapper>
      </body>
    </html>
  );
}
