-- AlterTable
ALTER TABLE `Kanban` ADD COLUMN `image` VARCHAR(191) NULL;

-- AlterTable
ALTER TABLE `TemplateDiagram` ADD COLUMN `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    ADD COLUMN `updatedAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3);

-- AlterTable
ALTER TABLE `TemplateOntology` ADD COLUMN `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    ADD COLUMN `updatedAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3);

-- AlterTable
ALTER TABLE `funnels` ADD COLUMN `image` VARCHAR(191) NULL;
